# Device
use_cuda: True
device_idx: '0'
num_workers: 4
seed: 17

# dataset
img_dir: './data/00000242.jpg'
mask_dir: './data/mask.png'   # for image inpainting

# task
task: 'Inpaint'  # 'Inpaint', 'SuperResolution' available
experiment_folder: './inpaint_exp'

# Network
cnum: 32

# Training
iterations: 3000
evaluation_step: 100
optim: 'adam'
lr: 1e-2
betas:
  - 0.5
  - 0.9

# task specific parameter
output_resolution:    # for SuperResolution
  - 1024     # height
  - 1024     # width
